credentials:
  usernames:
    pybot:
      email: pybot2024@gmail.com
      logged_in: False # Will be managed automatically
      name: pybot
      password: pybot
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
