#Add Alejandra's, Arnas', Iason's and the 5 students email later (10 testers in total of which 2 are white-box and 8 are black-box)
credentials:
  usernames:
    zceenko:
      email: zceenko@ucl.ac.uk
      logged_in: False # Will be managed automatically
      name: zceenko
      password: zceenko
    zceemc0:
      email: zceemc0@ucl.ac.uk
      logged_in: False # Will be managed automatically
      name: zceemc0
      password: zceemc0
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name