#Add Alejandra's, Arnas', Iason's and the 5 students email later (10 testers in total of which 2 are white-box and 8 are black-box)
email:
  user1: zceenko@ucl.ac.uk
  user2: zceemc0@ucl.ac.uk
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
